
[/Script/CommonUI.CommonUISettings]
CommonButtonAcceptKeyHandling=TriggerClick

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=7CC36FB3423E6EC646CA34AE74443A2B

[/Script/BattleDamagePlugin.BattleDamageSettings]
; 伤害数字显示Actor的Blueprint路径
DamageNumberActorPath=/Game/Niagara/DamageNumber/BP_DamageNumberActor.BP_DamageNumberActor_C

[/Script/TestWorld.TestWorldSettings]
CombatObjectConfigPath=/Game/Data/DA_CombatObjectConfig.DA_CombatObjectConfig

[/Script/ProjectilePlugin.ProjectileSettings]
; 箭矢渲染Actor的Blueprint路径
ProjectileActorPath=/Game/Weapon/BP/BP_ProjectileActor.BP_ProjectileActor_C